### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by Stephenfang51** [TemugeB/handpose3d#1]
Hi, excellent work

As for my understanding, you triangulate xy coordinate from two uv coordinates of two cameras, is that right ?

**Comment by TemugeB** [comment]
Hi, 

You can get the 3D xyz coordinates from uv pixel coordinates from two cameras.

**Comment by Stephenfang51** [comment]
@TemugeB  after calibration of two cameras, can I move two cameras during online?  or it just needed to be exactly the same position?

Thanks for quick response !

**Comment by TemugeB** [comment]
That depends. You can't move one of the cameras, both cameras have to move exactly the same. This also means the 3D triangulated point is not with respect to a stationary origin. To get 3D point, you also need to compensate for how the cameras are moving with respect to the origin. But maybe you don't care about 3D coordinate with respect to some world origin. You can use one of the cameras as your world origin, in which case you can move both cameras and the 3D coordinates will still be with respect to what the camera sees.

**Comment by Stephenfang51** [comment]
@TemugeB  Thanks ! really helpful, I plan to use this method for annotation of  3D Hand Pose, what do you think ?
