### ISSUE TITLE
Suggestion for joint angle calculcation

### ISSUE THREAD

**Issue by terrylincn** [TemugeB/handpose3d#2]
Hi, do you have any plan to implement the calculation of the joint angle for the handpose like the one you did for bodypose?

**Comment by TemugeB** [comment]
No, I'm not planning to add joint angles to hand poses. You can try to follow the template I made for the body pose package. It should be noted that the hand can self occlude a lot more than the body can, which means in general hand keypoints are a lot more noisy than body keypoints detection.
